#!/usr/bin/env python3
"""Batch-create GitHub issues for the combined red-team audit."""

import subprocess
import sys

REPO = "Celerio-sg/ATSassin"


def create_issue(title: str, body: str, labels: str):
    cmd = [
        "gh", "issue", "create", "--repo", REPO,
        "--title", title,
        "--body", body,
        "--label", labels,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"FAILED: {title}")
        print(result.stderr)
        return False
    print(f"OK: {title} -> {result.stdout.strip()}")
    return True


issues = [
    {
        "title": "[CRITICAL] Distillation conversion scripts are non-functional stubs",
        "body": """The `export_onnx.py`, `quantize_gguf.sh`, and `openvino_export.py` scripts generated by `atsassin distill` only print placeholder messages and do not perform real conversion.

Permanent fix required
- Implement actual ONNX export using `transformers.onnx` or `optimum[onnxruntime]`.
- Implement GGUF quantization by calling `llama.cpp` conversion scripts (e.g. `convert-hf-to-gguf.py`) with sensible defaults.
- Implement OpenVINO IR export using `openvino.convert_model` / `openvino.save_model`.
- Generated scripts must validate dependencies, report actionable errors, and exit non-zero on failure.
- Add tests that exercise the generated scripts on a tiny fixture model.

Acceptance criteria
- [ ] Running `export_onnx.py <dir>` produces a valid `.onnx` file.
- [ ] Running `quantize_gguf.sh <dir>` produces a valid `.gguf` file.
- [ ] Running `openvino_export.py <dir>` produces valid `.xml`/`.bin` IR files.
- [ ] CI tests verify the generated scripts are not stubs.
""",
        "labels": "bug,area:distillation",
    },
    {
        "title": "[CRITICAL] Lightning AI integration is stubbed and never trains",
        "body": """When `LlmProvider::Lightning` is selected, `atsassin distill` prints a stub note and never submits the training data to Lightning AI.

Permanent fix required
- Implement a Lightning AI training client in `src/engine/lightning.rs`.
- Authenticate with `LIGHTNING_API_KEY` and `LIGHTNING_BASE_URL`.
- Upload the generated `training_pairs.jsonl` and submit a fine-tuning job.
- Poll or return the job ID/status and surface errors to the CLI.
- Add unit tests with mocked HTTP responses.

Acceptance criteria
- [ ] `atsassin distill` with `provider = "lightning"` submits the JSONL.
- [ ] Job ID and status are printed.
- [ ] Errors from the Lightning AI API are propagated.
- [ ] Tests cover success, auth failure, and upload failure paths.
""",
        "labels": "bug,area:llm",
    },
    {
        "title": "[HIGH] Daemon is scan-only and not a full orchestrator",
        "body": """`src/engine/daemon.rs` only scans boards. The autonomous-loop design specifies that the daemon should also evaluate/rank jobs, queue high-quality jobs for tailoring, trigger follow-ups, and ingest outcomes from email/IMAP.

Permanent fix required
- Extend `run_tick` into a state-machine workflow.
- After scanning, evaluate new jobs against the user profile.
- Rank with `landscore` and queue top matches for tailoring.
- Update pipeline statuses and trigger follow-up reminders.
- Periodically sync IMAP outcomes.
- Keep the hardware-gating: skip heavy steps on `light` tier.

Acceptance criteria
- [ ] Daemon evaluates new jobs after scanning.
- [ ] Daemon ranks and queues top matches for tailoring.
- [ ] Daemon triggers follow-up reminders based on pipeline status.
- [ ] Daemon ingests IMAP outcomes.
- [ ] Tests cover each daemon step independently.
""",
        "labels": "enhancement,area:daemon,design:autonomous-loop",
    },
    {
        "title": "[HIGH] Add PII scrubbing to LoRA sharing pipeline",
        "body": """The autonomous LoRA sharing design plans to pool distilled adapters across users, but the export path does not yet scrub PII before any artifact leaves the local machine.

Permanent fix required
- Integrate `src/engine/pii_scrubber.rs` into every artifact export and registry upload path.
- Add a gate that blocks export until `contains_pii` returns false.
- Surface user-facing logs describing what was redacted and why.
- Add tests proving PII cannot leak through the export path.

Acceptance criteria
- [ ] `PiiScrubber` runs on all exported JSONL/manifests/adapters.
- [ ] Export is blocked if PII is detected after scrubbing.
- [ ] Logs report redacted fields.
- [ ] Regression tests cover names, emails, phones, addresses, and company names.
""",
        "labels": "enhancement,area:privacy,design:autonomous-loop",
    },
    {
        "title": "[HIGH] Standardize on rustls and remove OpenSSL dependency via imap crate",
        "body": """The codebase uses `rustls` for HTTP but the `imap` crate pulls in `native-tls` and OpenSSL, increasing supply-chain and platform-build risk.

Permanent fix required
- Switch `imap` to a `rustls`-enabled feature, or replace with a rustls-native IMAP implementation.
- Update `Cargo.toml` to eliminate `native-tls` / OpenSSL.
- Add `cargo-deny` or `cargo-audit` to CI to prevent regressions.
- Document the rationale.

Acceptance criteria
- [ ] No OpenSSL / native-tls in the dependency tree.
- [ ] IMAP outcome sync still works.
- [ ] CI runs `cargo-deny` or `cargo-audit`.
""",
        "labels": "enhancement,area:security,help wanted",
    },
    {
        "title": "[HIGH] Implement board-health canary for scraper drift detection",
        "body": """Scraper drift is only detected manually. The roadmap calls for an automated canary that detects zero-result boards and structural changes.

Permanent fix required
- Implement a `board_health` module with a small probe set.
- Compare current results to baselines.
- Issue warnings/alerts when drift exceeds a threshold.
- Wire into `atsassin daemon` and/or CI.

Acceptance criteria
- [ ] Canary scrapes probe boards and records result counts.
- [ ] Drift beyond threshold raises an alert (log/issue/notification).
- [ ] Tests validate detection logic without network calls.
""",
        "labels": "enhancement,area:scraper,good first issue,help wanted",
    },
    {
        "title": "[MEDIUM] Add startup validation of required secrets",
        "body": """Missing API keys or IMAP credentials are only discovered at runtime, often mid-operation.

Permanent fix required
- Validate that required secrets are present for the selected provider at startup.
- Fail fast with a clear, actionable error message.
- Add tests for each provider configuration.

Acceptance criteria
- [ ] Missing `*_API_KEY` for a paid provider fails at startup.
- [ ] Missing IMAP credentials fail at startup only when IMAP is used.
- [ ] Tests cover valid and invalid configurations.
""",
        "labels": "enhancement,area:config,good first issue",
    },
    {
        "title": "[MEDIUM] Add `atsassin health` command",
        "body": """There is no single command that validates LLM, database, network, and IMAP connectivity.

Permanent fix required
- Add `atsassin health` that checks: LLM connectivity, database read/write, network reachability, IMAP connectivity (if configured), and disk space.
- Return structured output and a non-zero exit code on failure.

Acceptance criteria
- [ ] `atsassin health` runs all checks.
- [ ] Each check reports pass/fail with a reason.
- [ ] Exit code is non-zero if any critical check fails.
- [ ] Tests use mocks for network calls.
""",
        "labels": "enhancement,area:cli,good first issue",
    },
    {
        "title": "[MEDIUM] Sanitize user-provided text before it enters LLM prompts",
        "body": """Profile and job-description text is inserted into prompts without length limits or delimiting checks, risking token overflow and prompt-injection-style misuse.

Permanent fix required
- Add length caps, boundary markers, and a small `InputSanitizer`.
- Reject or truncate suspiciously nested instructions.
- Apply in `src/engine/prompts.rs`, `tailor.rs`, and `scorer.rs`.

Acceptance criteria
- [ ] Prompt inputs are capped to a configurable max length.
- [ ] Boundary markers separate user content from instructions.
- [ ] Nested instruction patterns are detected and rejected.
- [ ] Tests cover overflow and injection attempts.
""",
        "labels": "enhancement,area:security,area:llm",
    },
    {
        "title": "[MEDIUM] Add README sync check to CI",
        "body": """New CLI commands are not automatically checked against README documentation, so docs can drift.

Permanent fix required
- Add a CI step that extracts commands from README and verifies they exist in `atsassin --help` output.
- Fail the build if a documented command is missing.

Acceptance criteria
- [ ] CI job runs README sync check.
- [ ] Build fails when a README command does not exist.
""",
        "labels": "documentation,good first issue,area:ci",
    },
    {
        "title": "[MEDIUM] Validate low-spec/CPU-only hardware claim on real hardware",
        "body": """The documented 4GB CPU-only target has not been validated on real hardware.

Permanent fix required
- Add a CI job or documented manual protocol that runs the full CLI on a 4GB CPU-only machine.
- Assert acceptable latency and memory usage.
- Record results in a test report.

Acceptance criteria
- [ ] Protocol documented in `docs/`.
- [ ] Validation run recorded.
- [ ] Regressions are flagged.
""",
        "labels": "good first issue,help wanted,area:hardware",
    },
    {
        "title": "[LOW] Make circuit breaker parameters configurable per provider",
        "body": """Circuit breaker threshold (5 failures) and cooldown (60s) are hard-coded constants in `src/engine/llm.rs`.

Permanent fix required
- Add per-provider configuration for threshold and cooldown.
- Use sensible defaults.
- Validate values at startup.

Acceptance criteria
- [ ] Config exposes threshold and cooldown.
- [ ] Different providers can have different values.
- [ ] Tests verify behavior with custom values.
""",
        "labels": "enhancement,area:llm,good first issue",
    },
    {
        "title": "[LOW] Add circuit breaker state-transition metrics to telemetry",
        "body": """Circuit breaker state transitions are not emitted to telemetry, limiting operational visibility.

Permanent fix required
- Emit events on open/close/half-open transitions.
- Include provider name and reason.

Acceptance criteria
- [ ] State transitions are recorded in telemetry.
- [ ] Tests assert events are emitted.
""",
        "labels": "enhancement,area:telemetry,good first issue",
    },
    {
        "title": "[LOW] Add opt-in SQLite encryption-at-rest",
        "body": """The local SQLite database is unencrypted, which is a risk for users syncing to cloud storage.

Permanent fix required
- Add opt-in encryption-at-rest using SQLCipher or similar.
- Keep default local-first, zero-friction behavior unchanged.
- Document key management.

Acceptance criteria
- [ ] Opt-in encryption can be enabled.
- [ ] Unencrypted databases still work.
- [ ] Documentation covers key management.
""",
        "labels": "enhancement,area:privacy,help wanted",
    },
    {
        "title": "[LOW] Evaluate RwLock or connection pool for database access",
        "body": """`src/pipeline/tracker.rs` uses `Mutex<Connection>`. Read-heavy workloads may contend on the single mutex.

Permanent fix required
- Evaluate `RwLock` or a small connection pool.
- Measure contention before/after.
- Keep correctness guarantees.

Acceptance criteria
- [ ] Benchmark or reasoning documented.
- [ ] Change implemented if it improves performance without adding risk.
""",
        "labels": "enhancement,area:performance,help wanted",
    },
    {
        "title": "[LOW] Add disk space checks before large operations",
        "body": """Archival and distillation operations can exhaust disk.

Permanent fix required
- Add pre-flight disk-space checks before large writes.
- Fail fast with a clear message.
- Add tests with mocked filesystems.

Acceptance criteria
- [ ] Large operations check available space.
- [ ] Clear error when space is insufficient.
- [ ] Tests cover low-space path.
""",
        "labels": "enhancement,area:reliability,good first issue",
    },
    {
        "title": "[LOW] Replace `.expect()` calls in HTTP client construction",
        "body": """Some HTTP client construction in `src/engine/llm.rs` uses `.expect()` or `.unwrap()` where failure should be propagated.

Permanent fix required
- Replace with `anyhow`-style error propagation.
- Document any remaining cases where panic is genuinely unrecoverable.

Acceptance criteria
- [ ] No new panics introduced.
- [ ] Tests cover error paths.
""",
        "labels": "enhancement,area:llm,good first issue",
    },
    {
        "title": "[LOW] Add structured error codes for common failures",
        "body": """Errors are currently stringly typed, making programmatic handling difficult.

Permanent fix required
- Add machine-readable error codes for common failure scenarios.
- Surface codes in CLI output and telemetry.

Acceptance criteria
- [ ] Error codes defined in a central enum.
- [ ] Common failures have stable codes.
- [ ] CLI can optionally output JSON with codes.
""",
        "labels": "enhancement,area:errors,good first issue",
    },
    {
        "title": "[LOW] Expand PII scrubber for international formats and edge cases",
        "body": """International phone formats and unusual address formats may not be caught by the current regex-based scrubber.

Permanent fix required
- Expand regex coverage.
- Add tests for international phones, non-US addresses, and Unicode names.

Acceptance criteria
- [ ] International phone numbers are scrubbed.
- [ ] Non-US addresses are scrubbed.
- [ ] Regression tests added.
""",
        "labels": "enhancement,area:privacy,good first issue",
    },
    {
        "title": "[LOW] Document all environment variables in one place",
        "body": """Secrets and environment overrides are scattered across source files.

Permanent fix required
- Centralize documentation of all environment variables in `docs/ENVIRONMENT.md`.
- Keep it in sync with code via CI if possible.

Acceptance criteria
- [ ] Every `std::env::var` usage is documented.
- [ ] Document includes required vs optional and example values.
""",
        "labels": "documentation,good first issue",
    },
    {
        "title": "[LOW] Add configuration backup and rollback mechanism",
        "body": """Successful config modifications are not backed up, risking accidental corruption.

Permanent fix required
- Back up `config.toml` before modifying.
- Provide a rollback command or flag.
- Add tests.

Acceptance criteria
- [ ] Config is backed up before write.
- [ ] Rollback command restores previous version.
- [ ] Tests cover backup and rollback.
""",
        "labels": "enhancement,area:reliability,good first issue",
    },
]


def main():
    for issue in issues:
        create_issue(issue["title"], issue["body"], issue["labels"])


if __name__ == "__main__":
    main()
